export const const_actions = ['free', '1', '2', '3', 'reaction']
export const const_traditions = ['arcane', 'divine', 'occult', 'primal'];

export const const_components = {
  full: [
    "10 minutes",
    "1 minute",
    "1 hour",
    "or",
    "material",
    "somatic",
    "verbal",
    "focus",
    "5 minutes",
  ],
  times: [
    "1 minute",
    "5 minutes",
    "10 minutes",
    "1 hour",
  ],
  requirements: [
    "verbal",
    "somatic",
    "material",
    "focus"
  ],
  separator: "or"
}

export const const_traits = [
  {category: "alignment", traits: [
    'good',
    'evil',
    'chaotic',
  ]},
  {category: "classes", traits: [
    'bard',
    'champion',
    'cleric',
    'druid',
    'monk',
    'oracle',
    'ranger',
    'sorcerer',
    'witch',
    'wizard',
  ]},
  {category: "effect", traits: [
    'arcane',
    'cold',
    'consecration',
    'darkness',
    'death',
    'detection',
    'emotion',
    'extradimensional',
    'fear',
    'fire',
    'force',
    'fortune',
    'healing',
    'morph',
    'move',
    'poison','air',
    'plant',
    'positive',
    'potion',
    'scrying',
    'sonic',
    'water',
    'earth',
    'negative',
    'teleportation',
    'disease',
    'misfortune',
    'acid',
    'divine',
    'possession',
    'polymorph',
    'incapacitation',
    'electricity',
    'mindless',
    'sleep',
    'prediction',
    'shadow',
    'curse',
    'light',
  ]},
  {category: "misc.", traits: [
    'archetype',
    'composition',
    'hex',
    'cantrip',
    'attack',
    'metamagic',
    'concentrate',
    'auditory',
    'visual',
    'humanoid',
    'mental',
    'stance',
    'litany',
    'nonlethal',
    'aura',
    'linguistic',
    'cursebound',
    'revelation',
    'fungus',
  ]},
  {category: "rarity", traits: [
    'uncommon',
    'rare',
  ]},
  {category: "school", traits: [
    'abjuration',
    'conjuration',
    'divination',
    'enchantment',
    'evocation',
    'illusion',
    'necromancy',
    'transmutation',
  ]}
];